version: "3.7"

services:
  nginx:
    restart: always
    container_name: d-sm-web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9080:80"
          - "9443:443"
    networks:
      - sm-bridge
